<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 C:\Coding\Other\advent-of-blep\static\models\minecraft-xmas-chest.glb --root /models/ --types --shadows --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group } from "three";
  import {
    T,
    type Props,
    type Events,
    type Slots,
    forwardEventHandlers,
  } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  type $$Props = Props<THREE.Group>;
  type $$Events = Events<THREE.Group>;
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

  export const ref = new Group();

  type GLTFResult = {
    nodes: {
      node_1: THREE.Mesh;
      node_2: THREE.Mesh;
    };
    materials: {
      ["12212233865295422202"]: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>("/models/minecraft-xmas-chest.glb");
  gltf.subscribe((result) => {
    if (!result) return;
    Object.keys(result.nodes).forEach((key) => {
      const node = result.nodes[key];
      node.computeVertexNormals();
    });
  });

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.1}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.node_1.geometry}
        material={gltf.materials["12212233865295422202"]}
        position={[-8, 0, -8]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.node_2.geometry}
        material={gltf.materials["12212233865295422202"]}
        position={[-8, 0, -8]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
