<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 C:\Coding\Other\advent-of-blep\static\models\tubbs-copyright-in-fridge.gltf --root /models/ --types --shadows --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group } from "three";
  import {
    T,
    type Props,
    type Events,
    type Slots,
    forwardEventHandlers,
  } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  type $$Props = Props<THREE.Group>;
  type $$Events = Events<THREE.Group>;
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

  export const ref = new Group();

  type GLTFResult = {
    nodes: {
      node_1: THREE.Mesh;
      node_1_1: THREE.Mesh;
    };
    materials: {
      ["12212233867087225693"]: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>("/models/tubbs-copyright-in-fridge.gltf");
  gltf.subscribe((result) => {
    if (!result) return;
    Object.keys(result.nodes).forEach((key) => {
      const node = result.nodes[key];
      if (node.computeVertexNormals) {
        node.computeVertexNormals();
      }
    });
  });

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.node_1.geometry}
      material={gltf.materials["12212233867087225693"]}
      position={[-32, 0, -32]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.node_1_1.geometry}
      material={gltf.materials["12212233867087225693"]}
      position={[-32, 0, -32]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
